### ISSUE TITLE
MVP 1 & 2 Complete

### ISSUE THREAD

**Issue by schen13** [schen13/Pintourist#2]
Setup account creation, login, and demo login
Deployed on heroku: https://pintouristapp.herokuapp.com/#/

**Comment by evhumphrey** [comment]
- [ ] Make sure to clear the errors between forms
  - hit signup with blank fields
  - errors will render
  - hit login 
  - errors should clear here 
- [ ] Style errors (right now they are plain) 
- Other than that, should be good!
